import { PropsWithChildren, ReactNode } from "react";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import Providers from "./providers";

import { cn } from "@/lib/utils";

import ThemeSelector from "@/components/ThemeSelector";

import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

interface Props {
  modal: ReactNode;
}

export default function RootLayout({ children, modal }: PropsWithChildren<Props>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <Providers>
          <ThemeSelector />
          {children}
          {modal}
        </Providers>
      </body>
    </html>
  );
}
